"""ccc-agent-setup: wire the pip-installed runtime into a system or user env.

`pip install ccc-agent-containment` places the Python package and the console
scripts (ccc-agent-run/launch/ctl) and bundles the shell hooks/shims as package
data.  pip cannot (and should not) write to /etc or register agent hooks, so
this command does that last-mile wiring:

  ccc-agent-setup --system   # /etc/ccc-agent/config.json + managed Claude
                             # settings + codex notify (run as root at image
                             # startup)
  ccc-agent-setup --user     # ~/.config/ccc-agent/config.json + ~/.claude
                             # settings hook (dev / non-CCC)

It resolves the bundled hooks via importlib.resources, so the registered paths
point into the installed package (under /usr for a system install, which the
bwrap sandbox exposes read-only).
"""

import argparse
import getpass
import json
import os
import stat
import sys
from importlib import resources
from shutil import which


def assets_dir():
    """On-disk path to the bundled shell assets (real files in a wheel install)."""
    return str(resources.files("ccc_agent").joinpath("assets"))


def _make_executable(path):
    try:
        mode = os.stat(path).st_mode
        os.chmod(path, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError:
        pass


def _resolve(name, override=None, fallbacks=()):
    if override:
        return override
    found = which(name)
    if found:
        return found
    for cand in fallbacks:
        if cand and os.path.exists(cand):
            return cand
    return name  # bare name: resolved on PATH at runtime


def _write_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        json.dump(data, fh, indent=2)
    os.chmod(path, 0o644)


_SECRETS = [".ssh", ".gnupg", ".netrc", ".aws", ".kube", ".docker/config.json"]


def build_config(mode, user, home, branchfs_bin, bwrap_bin, state_dir,
                 storage_root="/storage", branch_store="/opt/branchfs_branches",
                 container_name=""):
    """Assemble the runtime config.json (bwrap confinement by default).

    System mode models CCC's storage layout: the whole of ``/storage`` is the
    single BranchFS underlay (read-through), branched ONCE into a node-local
    delta store, and mounted back at ``/storage`` inside the sandbox.  CCC also
    bind-mounts the user's home to the same bytes as
    ``/storage/user/<container>`` -- so instead of branching that data a second
    time, we point ``$HOME`` at that subdir of the single branch (``home_subdir``
    on the root drives the in-sandbox ``$HOME`` bind; the top-level
    ``home_subdir`` drives the policy alias ``/home/<user>`` ->
    ``/storage/user/<container>``).  The store and state_dir therefore MUST live
    outside ``/storage`` (else BranchFS would branch its own state and the agent
    would see it)."""
    if mode == "system":
        container = container_name or user
        home_rel = "user/%s" % container                     # rel to /storage branch
        home_abs = "%s/%s" % (storage_root.rstrip("/"), home_rel)
        hide_paths = ["%s/%s" % (home_rel, s) for s in _SECRETS]
        # If state_dir happens to sit under the underlay, hide it from the view.
        sr = storage_root.rstrip("/")
        if state_dir.rstrip("/").startswith(sr + "/"):
            hide_paths.append(state_dir.rstrip("/")[len(sr) + 1:])
        root = {
            "name": "storage",
            "base": storage_root,                            # /storage (read-through)
            "store": os.path.join(branch_store, "storage"),  # node-local deltas
            "visible": storage_root,                         # mounted back at /storage
            "home_subdir": home_rel,                         # branch/<rel> -> /home/<user>
            "hide_paths": hide_paths,
        }
        top_home_subdir = container                          # alias /home/<user> -> /storage/user/<container>
        workspace = "/home/%s" % user
        ignore = ["%s/.codex*" % home_abs, "%s/.claude*" % home_abs,
                  "%s/.config*" % home_abs, "%s/.cache*" % home_abs]
    else:  # user mode: protect the real home
        root = {
            "name": "home", "base": home, "store": os.path.join(state_dir,
                                                                "stores", "home"),
            "visible": home, "home_subdir": "",
            "hide_paths": _SECRETS + [".ccc-agent"],
        }
        top_home_subdir = ""
        workspace = home
        ignore = [os.path.join(home, ".codex*"), os.path.join(home, ".claude*"),
                  os.path.join(home, ".config*"), os.path.join(home, ".cache*")]
    return {
        "_comment": "Generated by ccc-agent-setup. Keep root-owned and not "
                    "writable by agents.",
        "state_dir": state_dir,
        "backend": "branchfs",
        "branchfs_bin": branchfs_bin,
        "user": user,
        "home_subdir": top_home_subdir,
        "workspace": workspace,
        "confinement": "bwrap",
        "bwrap_bin": bwrap_bin,
        "bwrap_proc_mode": "bind",
        "_runtime_comment": "Re-expose the agent binary/runtime read-only at a "
                            "NON-view dest (e.g. '/path/to/agent:/opt/agent').",
        "bwrap_ro_binds": [],
        "_cred_comment": "Agents read auth from these dirs (re-exposed "
                         "read-only). OAuth logins authenticate from the token "
                         "file, so do NOT mask it; cred_mask+cred_env are for "
                         "API-key auth.",
        "cred_mounts": [os.path.join(home, ".codex"),
                        os.path.join(home, ".claude")],
        "cred_mask": [],
        "cred_env": {},
        "roots": [root],
        "hide_patterns": [".env", ".env.*", "*.pem", "id_rsa*", "id_ed25519*",
                          "credentials.json"],
        "policy": {"mode": "workspace-auto", "ignore_patterns": ignore},
    }


def register_claude_managed(path, hook_cmd):
    """System: a managed-settings file the agent cannot rewrite."""
    _write_json(path, {"hooks": {"Stop": [{"hooks": [
        {"type": "command", "command": hook_cmd}]}]}})


def register_claude_user(path, hook_cmd):
    """User: merge the Stop hook into ~/.claude/settings.json (idempotent)."""
    settings = {}
    if os.path.exists(path):
        try:
            with open(path) as fh:
                settings = json.load(fh)
        except (ValueError, OSError):
            settings = {}
    stop = settings.setdefault("hooks", {}).setdefault("Stop", [])
    for matcher in stop:
        for h in matcher.get("hooks", []):
            if h.get("command") == hook_cmd:
                return  # already registered
    stop.append({"hooks": [{"type": "command", "command": hook_cmd}]})
    _write_json(path, settings)


def register_codex_notify(config_toml, hook_cmd):
    """Append the notify program to codex's config.toml if not already set."""
    existing = ""
    if os.path.exists(config_toml):
        with open(config_toml) as fh:
            existing = fh.read()
    if any(line.lstrip().startswith("notify") for line in existing.splitlines()):
        return  # respect an existing notify
    os.makedirs(os.path.dirname(config_toml), exist_ok=True)
    with open(config_toml, "a") as fh:
        fh.write('\nnotify = ["%s"]\n' % hook_cmd)


def main(argv=None):
    parser = argparse.ArgumentParser(
        prog="ccc-agent-setup",
        description="Wire the installed ccc-agent runtime (config + hooks).")
    parser.add_argument("--system", action="store_true",
                        help="system install (/etc, managed settings; root)")
    parser.add_argument("--user", action="store_true",
                        help="user install (~/.config, ~/.claude)")
    parser.add_argument("--config", help="config.json path (override)")
    parser.add_argument("--user-name", help="agent user (default: current)")
    parser.add_argument("--branchfs-bin")
    parser.add_argument("--bwrap-bin")
    parser.add_argument("--state-dir")
    parser.add_argument("--storage-root", default="/storage",
                        help="real BranchFS underlay (system mode); branched once")
    parser.add_argument("--branch-store", default="/opt/branchfs_branches",
                        help="node-local dir for BranchFS deltas (must be OUTSIDE "
                             "--storage-root)")
    parser.add_argument("--container-name",
                        help="CCC container name; $HOME maps to "
                             "<storage-root>/user/<container> (default: $CONTAINER_NAME)")
    parser.add_argument("--no-hooks", action="store_true",
                        help="skip registering agent hooks")
    parser.add_argument("--enable-shims", action="store_true",
                        help="symlink the transparent agent PATH shims")
    parser.add_argument("--shim-agents", default="codex claude hermes opencode")
    parser.add_argument("--link-dir", default="/usr/local/bin")
    args = parser.parse_args(argv)

    mode = "user" if args.user and not args.system else "system"
    assets = assets_dir()
    hooks = os.path.join(assets, "hooks")
    shims = os.path.join(assets, "shims")
    for name in os.listdir(hooks):
        _make_executable(os.path.join(hooks, name))
    _make_executable(os.path.join(shims, "ccc-agent-shim.sh"))

    user = args.user_name or os.environ.get("USER_NAME") or getpass.getuser()
    container_name = args.container_name or os.environ.get("CONTAINER_NAME") or ""
    if mode == "system":
        home = "/home/%s" % user
        # The state_dir holds the BranchFS *mountpoints*, so it MUST sit where the
        # CCC FUSE sidecar can mount -- i.e. under a Docker bind mount. The sidecar
        # translates client->host paths and refuses the container's overlay, so a
        # path like /opt/... fails the mount with EPERM (even as root: there is no
        # host-side bind mount to mount into). /storage/user is always such a bind
        # mount; it is inside the /storage underlay but build_config hides it from
        # the branch so BranchFS never recurses into it. For node-local speed,
        # point --state-dir at a bind-mounted local scratch, e.g.
        # /storage/local/ssd/.ccc-agent.
        state_dir = args.state_dir or "/storage/user/.ccc-agent"
        config_file = args.config or "/etc/ccc-agent/config.json"
        claude_settings = os.environ.get(
            "CLAUDE_MANAGED_SETTINGS", "/etc/claude-code/managed-settings.json")
    else:
        home = os.path.expanduser("~")
        state_dir = args.state_dir or os.path.join(home, ".ccc-agent")
        config_file = args.config or os.path.join(
            home, ".config", "ccc-agent", "config.json")
        claude_settings = os.path.join(home, ".claude", "settings.json")

    branchfs_bin = _resolve("branchfs", args.branchfs_bin,
                            ["/usr/local/bin/branchfs"])
    bwrap_bin = _resolve("bwrap", args.bwrap_bin)

    config = build_config(mode, user, home, branchfs_bin, bwrap_bin,
                          state_dir, args.storage_root, args.branch_store,
                          container_name)
    _write_json(config_file, config)
    sys.stderr.write("ccc-agent-setup: wrote %s\n" % config_file)

    if not args.no_hooks:
        claude_hook = os.path.join(hooks, "claude-stop-hook.sh")
        if mode == "system":
            register_claude_managed(claude_settings, claude_hook)
        else:
            register_claude_user(claude_settings, claude_hook)
        register_codex_notify(os.path.join(home, ".codex", "config.toml"),
                              os.path.join(hooks, "codex-notify.sh"))
        sys.stderr.write("ccc-agent-setup: registered claude + codex hooks\n")

    if args.enable_shims:
        os.makedirs(args.link_dir, exist_ok=True)
        shim = os.path.join(shims, "ccc-agent-shim.sh")
        for agent in args.shim_agents.split():
            link = os.path.join(args.link_dir, agent)
            try:
                if os.path.islink(link) or os.path.exists(link):
                    os.unlink(link)
                os.symlink(shim, link)
            except OSError as exc:
                sys.stderr.write("ccc-agent-setup: shim %s failed: %s\n"
                                 % (agent, exc))

    sys.stderr.write("ccc-agent-setup: done (%s mode)\n" % mode)
    return 0


if __name__ == "__main__":
    sys.exit(main())
