"""``ccc-agent setup``: wire the pip-installed runtime into a system/user env.

`pip install ccc-agent` places the Python package, the unified ``ccc-agent``
console script, and the shell hooks/shims as package
data. pip cannot (and should not) mutate a user's normal Codex/Claude config, so
this command writes ccc-agent-owned config plus confined-only hook snippets:

  ccc-agent setup --system   # /etc/ccc-agent/config.json + optional shims
  ccc-agent setup --user     # ~/.config/ccc-agent/config.json + optional shims

`ccc-agent run` consumes that config and bind-mounts bundled native agent
plugins read-only into bwrap only for a matching contained agent. Direct
codex/claude runs do not see or use CCC hooks.
The plugin entries point at bundled hook scripts under the installed package (under
/usr for a system install, which the bwrap sandbox exposes read-only).
"""

import argparse
import getpass
import json
import os
import stat
import sys
from importlib import resources
from shutil import which


def assets_dir():
    """On-disk path to the bundled shell assets (real files in a wheel install)."""
    return str(resources.files("ccc_agent").joinpath("assets"))


def plugins_dir():
    """On-disk path to the bundled agent plugin packages.

    These directories (codex-/claude-/hermes-ccc-containment) are root-owned and
    read-only in a system install; ccc-agent run bind-mounts the matching one
    read-only into the bwrap sandbox so a contained agent loads the CCC
    lifecycle hooks through its NATIVE plugin mechanism -- no edit of the user's
    ~/.codex/config.toml or ~/.claude/settings.json."""
    return os.path.join(assets_dir(), "plugins")


def _make_executable(path):
    try:
        mode = os.stat(path).st_mode
        os.chmod(path, mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError:
        pass


def _resolve(name, override=None, fallbacks=()):
    if override:
        return override
    found = which(name)
    if found:
        return found
    for cand in fallbacks:
        if cand and os.path.exists(cand):
            return cand
    return name  # bare name: resolved on PATH at runtime


def _write_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        json.dump(data, fh, indent=2)
    os.chmod(path, 0o644)


def _shell_single_quote(value):
    """Quote a string for POSIX shell single-quoted assignment."""
    return "'" + value.replace("'", "'\"'\"'") + "'"


def write_conda_shim_hooks(conda_prefix, shim_dir):
    """Install env-specific conda hooks that keep ccc shims first on PATH.

    Conda activation normally prepends ``$CONDA_PREFIX/bin``. If the ccc shims
    only live in /usr/local/bin, a conda-installed ``codex``/``claude`` wins and
    bypasses containment. These hooks run after conda's PATH mutation and
    re-prepend a trusted shim directory, while the shim itself skips that first
    PATH hit and resolves the real binary from the active env.
    """
    activate_dir = os.path.join(conda_prefix, "etc", "conda", "activate.d")
    deactivate_dir = os.path.join(conda_prefix, "etc", "conda", "deactivate.d")
    os.makedirs(activate_dir, exist_ok=True)
    os.makedirs(deactivate_dir, exist_ok=True)
    quoted = _shell_single_quote(os.path.abspath(shim_dir))
    activate = os.path.join(activate_dir, "ccc-agent-shims.sh")
    deactivate = os.path.join(deactivate_dir, "ccc-agent-shims.sh")
    with open(activate, "w") as fh:
        fh.write("#!/bin/sh\n"
                 "# Generated by ccc-agent setup. Keep containment shims ahead\n"
                 "# of $CONDA_PREFIX/bin so conda-installed agents are wrapped.\n"
                 "_CCC_AGENT_SHIM_DIR=%s\n"
                 "case \"$PATH\" in\n"
                 "    \"$_CCC_AGENT_SHIM_DIR\"|\"$_CCC_AGENT_SHIM_DIR\":*) ;;\n"
                 "    *) PATH=\"$_CCC_AGENT_SHIM_DIR:$PATH\" ;;\n"
                 "esac\n"
                 "export PATH\n"
                 "export CCC_AGENT_SHIM_DIR=\"$_CCC_AGENT_SHIM_DIR\"\n"
                 "unset _CCC_AGENT_SHIM_DIR\n" % quoted)
    with open(deactivate, "w") as fh:
        fh.write("#!/bin/sh\n"
                 "# Generated by ccc-agent setup. Remove the leading shim path\n"
                 "# this env's activate hook prepended.\n"
                 "_CCC_AGENT_SHIM_DIR=%s\n"
                 "case \"$PATH\" in\n"
                 "    \"$_CCC_AGENT_SHIM_DIR\") PATH=\"\" ;;\n"
                 "    \"$_CCC_AGENT_SHIM_DIR\":*) PATH=${PATH#\"$_CCC_AGENT_SHIM_DIR\":} ;;\n"
                 "esac\n"
                 "export PATH\n"
                 "unset CCC_AGENT_SHIM_DIR\n"
                 "unset _CCC_AGENT_SHIM_DIR\n" % quoted)
    os.chmod(activate, 0o755)
    os.chmod(deactivate, 0o755)
    return activate, deactivate


_SECRETS = [".ssh", ".gnupg", ".netrc", ".aws", ".kube", ".docker/config.json"]

# Neutral in-sandbox mount root for plugin packages (outside any BranchFS view,
# so bwrap does not mkdir mountpoints into the FUSE view).
SANDBOX_PLUGIN_ROOT = "/ccc-agent/plugins"


def build_agent_plugins(home, src_dir=None):
    """Describe per-agent CCC plugin injection (replaces the old config-file
    overlay ``agent_hooks``).  Each entry is consumed by ccc-agent run, which
    bind-mounts ``src`` read-only at ``sandbox_path`` for a matching contained
    agent, inserts ``argv`` right after the agent executable, and exports
    ``setenv`` into the sandbox.  Direct codex/claude/hermes runs get none of
    this; nothing under the user's real config is touched.

      claude  -- native ``--plugin-dir`` session-only plugin load (verified).
      codex   -- plugin dropped at the in-sandbox Codex plugin scan path; the
                 blocking Stop hook comes from the plugin's hooks/hooks.json.
                 ``argv`` is left tunable for the installed Codex version's
                 enable/trust flags; per-turn hooks are best-effort and fall
                 back to session-end review.
      hermes  -- native bundled-plugin dir via HERMES_BUNDLED_PLUGINS, with
                 HERMES_ACCEPT_HOOKS=1 to skip the interactive consent prompt.
    """
    src = src_dir or plugins_dir()
    codex_user_plugins = os.path.join(home, ".codex", "plugins")
    claude_sandbox = os.path.join(SANDBOX_PLUGIN_ROOT, "claude-ccc-containment")
    hermes_bundle_root = os.path.join(SANDBOX_PLUGIN_ROOT, "hermes")
    return {
        "codex": {
            "src": os.path.join(src, "codex-ccc-containment"),
            "sandbox_path": os.path.join(codex_user_plugins,
                                         "ccc-agent"),
            "ensure_dirs": [codex_user_plugins],
            "argv": [],
        },
        "claude": {
            "src": os.path.join(src, "claude-ccc-containment"),
            "sandbox_path": claude_sandbox,
            "argv": ["--plugin-dir", claude_sandbox],
        },
        "hermes": {
            "src": os.path.join(src, "hermes-ccc-containment"),
            "sandbox_path": os.path.join(hermes_bundle_root,
                                         "ccc-agent"),
            "setenv": {
                "HERMES_BUNDLED_PLUGINS": hermes_bundle_root,
                "HERMES_ACCEPT_HOOKS": "1",
            },
        },
    }


def build_agent_state_binds(home):
    """Default shared direct state for agent tools, outside BranchFS."""
    return [os.path.join(home, name)
            for name in (".codex", ".claude", ".hermes")]


def build_config(mode, user, home, branchfs_bin, bwrap_bin, state_dir,
                 storage_root="/storage", branch_store="/opt/branchfs_branches",
                 container_name=""):
    """Assemble the runtime config.json (bwrap confinement by default).

    System mode models CCC's storage layout: the whole of ``/storage`` is the
    single BranchFS underlay (read-through), branched ONCE into a node-local
    delta store, and mounted back at ``/storage`` inside the sandbox.  CCC also
    bind-mounts the user's home to the same bytes as
    ``/storage/user/<container>`` -- so instead of branching that data a second
    time, we point ``$HOME`` at that subdir of the single branch (``home_subdir``
    on the root drives the in-sandbox ``$HOME`` bind; the top-level
    ``home_subdir`` drives the policy alias ``/home/<user>`` ->
    ``/storage/user/<container>``).  The store and state_dir therefore MUST live
    outside ``/storage`` (else BranchFS would branch its own state and the agent
    would see it)."""
    if mode == "system":
        container = container_name or user
        home_rel = "user/%s" % container                     # rel to /storage branch
        home_abs = "%s/%s" % (storage_root.rstrip("/"), home_rel)
        hide_paths = ["%s/%s" % (home_rel, s) for s in _SECRETS]
        # If state_dir happens to sit under the underlay, hide it from the view.
        sr = storage_root.rstrip("/")
        if state_dir.rstrip("/").startswith(sr + "/"):
            hide_paths.append(state_dir.rstrip("/")[len(sr) + 1:])
        root = {
            "name": "storage",
            "base": storage_root,                            # /storage (read-through)
            "store": os.path.join(branch_store, "storage"),  # node-local deltas
            "visible": storage_root,                         # mounted back at /storage
            "home_subdir": home_rel,                         # branch/<rel> -> /home/<user>
            "hide_paths": hide_paths,
        }
        top_home_subdir = container                          # alias /home/<user> -> /storage/user/<container>
        ignore = ["%s/.cache*" % home_abs]
    else:  # user mode: protect the real home
        root = {
            "name": "home", "base": home, "store": os.path.join(state_dir,
                                                                "stores", "home"),
            "visible": home, "home_subdir": "",
            "hide_paths": _SECRETS + [".ccc-agent"],
        }
        top_home_subdir = ""
        ignore = [os.path.join(home, ".cache*")]
    agent_plugins = build_agent_plugins(home)
    return {
        "_comment": "Generated by ccc-agent setup. Keep root-owned and not "
                    "writable by agents.",
        "state_dir": state_dir,
        "backend": "branchfs",
        "branchfs_bin": branchfs_bin,
        "branchfs_timeout_seconds": 30,
        "user": user,
        "home_subdir": top_home_subdir,
        "_workspace_comment": (
            "Launch workspace is per invocation: ccc-agent run defaults to "
            "the caller's current directory; pass --workspace to override."),
        "confinement": "bwrap",
        "bwrap_bin": bwrap_bin,
        "bwrap_proc_mode": "bind",
        "_runtime_comment": "Re-expose the agent binary/runtime read-only at a "
                            "NON-view dest (e.g. '/path/to/agent:/opt/agent').",
        "bwrap_ro_binds": [],
        "_agent_state_comment": "By default ~/.codex, ~/.claude, and ~/.hermes "
                                "are shared rw system state, direct-bound over "
                                "the BranchFS home view and never committed or "
                                "rolled back by ccc-agent. Codex/Claude/Hermes "
                                "own their own concurrent access. Set "
                                "protect_agent_state=true or run with "
                                "--protect-agent-state to keep these dirs in "
                                "BranchFS review instead.",
        "protect_agent_state": False,
        "ensure_agent_state_dirs": True,
        "agent_state_binds": build_agent_state_binds(home),
        "_cred_comment": "Agent config/state dirs such as ~/.codex, "
                         "~/.claude, and ~/.hermes are direct shared rw "
                         "agent_state_binds by default, so real agents can "
                         "create logs, sessions, caches, config, and refreshed "
                         "tokens without BranchFS merge policy. Use cred_mounts "
                         "only for narrow special-case read-only overlays; do "
                         "not bind the whole agent state dirs read-only by "
                         "default.",
        "cred_mounts": [],
        "cred_mask": [],
        "cred_env": {},
        "_agent_plugins_comment": "Native CCC lifecycle-hook plugins, injected "
                                  "read-only into bwrap ONLY for a matching "
                                  "contained agent (codex/claude/hermes). The "
                                  "launcher mounts 'src' at 'sandbox_path', "
                                  "inserts 'argv' after the agent executable, "
                                  "and exports 'setenv'. Direct codex/claude/"
                                  "hermes runs load none of this and the user's "
                                  "own config is never edited or hidden.",
        "agent_hook_mode": "plugins",
        "agent_plugins": agent_plugins,
        "roots": [root],
        "hide_patterns": [".env", ".env.*", "*.pem", "id_rsa*", "id_ed25519*",
                          "credentials.json"],
        "policy": {"mode": "workspace-auto", "ignore_patterns": ignore},
    }


def main(argv=None, prog="ccc-agent setup"):
    parser = argparse.ArgumentParser(
        prog=prog,
        description="Wire the installed ccc-agent runtime (config + hooks).")
    parser.add_argument("--system", action="store_true",
                        help="system install (/etc/ccc-agent; root)")
    parser.add_argument("--user", action="store_true",
                        help="user install (~/.config/ccc-agent)")
    parser.add_argument("--config", help="config.json path (override)")
    parser.add_argument("--user-name", help="agent user (default: current)")
    parser.add_argument("--branchfs-bin")
    parser.add_argument("--bwrap-bin")
    parser.add_argument("--state-dir")
    parser.add_argument("--storage-root", default="/storage",
                        help="real BranchFS underlay (system mode); branched once")
    parser.add_argument("--branch-store", default="/opt/branchfs_branches",
                        help="node-local dir for BranchFS deltas (must be OUTSIDE "
                             "--storage-root)")
    parser.add_argument("--container-name",
                        help="CCC container name; $HOME maps to "
                             "<storage-root>/user/<container> (default: $CONTAINER_NAME)")
    parser.add_argument("--no-agent-plugins", "--no-hooks", dest="no_plugins",
                        action="store_true",
                        help="omit the confined-only CCC agent plugin entries "
                             "(--no-hooks kept as a deprecated alias)")
    parser.add_argument("--protect-agent-state", action="store_true",
                        help="generate config with ~/.codex, ~/.claude, and "
                             "~/.hermes kept inside BranchFS review instead "
                             "of direct shared rw binds")
    parser.add_argument("--enable-shims", action="store_true",
                        help="symlink the transparent agent PATH shims")
    parser.add_argument("--shim-agents", default="codex claude hermes opencode")
    parser.add_argument("--link-dir", default="/usr/local/bin")
    parser.add_argument("--conda-prefix",
                        help="conda env prefix for --conda-activate-shims "
                             "(default: $CONDA_PREFIX)")
    parser.add_argument("--conda-activate-shims", action="store_true",
                        help="write conda activate/deactivate hooks that prepend "
                             "--link-dir so shims win over $CONDA_PREFIX/bin")
    args = parser.parse_args(argv)

    mode = "user" if args.user and not args.system else "system"
    assets = assets_dir()
    hooks = os.path.join(assets, "hooks")
    shims = os.path.join(assets, "shims")
    for name in os.listdir(hooks):
        _make_executable(os.path.join(hooks, name))
    _make_executable(os.path.join(shims, "ccc-agent-shim.sh"))
    # Plugin-bundled hook scripts must stay executable through the read-only
    # bwrap mount (pip can drop the +x bit on package data).
    for root, _dirs, files in os.walk(plugins_dir()):
        for name in files:
            if name.endswith(".sh"):
                _make_executable(os.path.join(root, name))

    user = args.user_name or os.environ.get("USER_NAME") or getpass.getuser()
    container_name = args.container_name or os.environ.get("CONTAINER_NAME") or ""
    if mode == "system":
        home = "/home/%s" % user
        # The state_dir holds the BranchFS *mountpoints*, so it MUST sit where the
        # CCC FUSE sidecar can mount -- i.e. under a Docker bind mount. The sidecar
        # translates client->host paths and refuses the container's overlay, so a
        # path like /opt/... fails the mount with EPERM (even as root: there is no
        # host-side bind mount to mount into). /storage/user is always such a bind
        # mount; it is inside the /storage underlay but build_config hides it from
        # the branch so BranchFS never recurses into it. For node-local speed,
        # point --state-dir at a bind-mounted local scratch, e.g.
        # /storage/local/ssd/.ccc-agent.
        state_dir = args.state_dir or "/storage/user/.ccc-agent"
        config_file = args.config or "/etc/ccc-agent/config.json"
    else:
        home = os.path.expanduser("~")
        state_dir = args.state_dir or os.path.join(home, ".ccc-agent")
        config_file = args.config or os.path.join(
            home, ".config", "ccc-agent", "config.json")

    branchfs_bin = _resolve("branchfs", args.branchfs_bin,
                            ["/usr/local/bin/branchfs"])
    bwrap_bin = _resolve("bwrap", args.bwrap_bin)

    config = build_config(mode, user, home, branchfs_bin, bwrap_bin,
                          state_dir, args.storage_root, args.branch_store,
                          container_name)
    if args.protect_agent_state:
        config["protect_agent_state"] = True
    if args.no_plugins:
        config["agent_plugins"] = {}
        config["agent_hook_mode"] = "disabled"
    else:
        sys.stderr.write(
            "ccc-agent setup: agent plugins reference bundled assets under %s "
            "(read-only, injected per contained run)\n" % plugins_dir())

    _write_json(config_file, config)
    sys.stderr.write("ccc-agent setup: wrote %s\n" % config_file)

    if args.enable_shims:
        os.makedirs(args.link_dir, exist_ok=True)
        shim = os.path.join(shims, "ccc-agent-shim.sh")
        for agent in args.shim_agents.split():
            link = os.path.join(args.link_dir, agent)
            try:
                if os.path.islink(link) or os.path.exists(link):
                    os.unlink(link)
                os.symlink(shim, link)
            except OSError as exc:
                sys.stderr.write("ccc-agent setup: shim %s failed: %s\n"
                                 % (agent, exc))

    if args.conda_activate_shims:
        conda_prefix = args.conda_prefix or os.environ.get("CONDA_PREFIX")
        if not conda_prefix:
            sys.stderr.write("ccc-agent setup: --conda-activate-shims needs "
                             "--conda-prefix or CONDA_PREFIX\n")
            return 2
        activate, deactivate = write_conda_shim_hooks(conda_prefix, args.link_dir)
        sys.stderr.write("ccc-agent setup: wrote conda shim hooks %s and %s\n"
                         % (activate, deactivate))

    sys.stderr.write("ccc-agent setup: done (%s mode)\n" % mode)
    return 0


if __name__ == "__main__":
    sys.exit(main())
